version: '3.5'
networks:
  credit-line-analyser-app:
    name: credit-line-analyser-app

services:
  redis:
    image: docker.io/bitnami/redis:6.2
    environment:
      - REDIS_PASSWORD=uU23o#0TU#BtNycSFv
    ports:
      - '6379:6379'
    volumes:
      - 'redis_data:/bitnami/redis/data'
    networks:
      - credit-line-analyser-app

  credit-line-analyser-app-web:
    build:
      context: .
      dockerfile: src/CreditLineAnalyser.Web/Dockerfile
    restart: on-failure
    depends_on:
      - redis
    ports:
      - "5086:80"
      - "7154:443"
    networks:
      - credit-line-analyser-app

volumes:
  redis_data:
    driver: local
